name: Build .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x       
    - name: Restore dependencies
      run: dotnet restore WebCon.BpsExt.Signing.AdobeSign.sln
    - name: Build
      run: dotnet build WebCon.BpsExt.Signing.AdobeSign.sln  --no-restore --configuration Release 
    - uses: actions/upload-artifact@v4
      with:
        name: WebCon.BpsExt.Signing.AdobeSign${{ matrix.runs-on }}
        path: |
          AdobeSignIntegration/bin/Release/net9.0/WebCon.BpsExt.Signing.AdobeSign.dll
          AdobeSignIntegration/bin/Release/net9.0/WebCon.BpsExt.Signing.AdobeSign.json
          AdobeSignIntegration/bin/Release/net9.0/Newtonsoft.Json.dll
          
