<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>WebCon.BpsExt.Signing.AdobeSign</RootNamespace>
    <AssemblyName>WebCon.BpsExt.Signing.AdobeSign</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>tmpKey.snk</AssemblyOriginatorKeyFile>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CustomActions\AllStatus\CheckAllDocStatusAction.cs" />
    <Compile Include="CustomActions\AllStatus\CheckAllDocStatusActionConfig.cs" />
    <Compile Include="CustomActions\Delete\DeleteAgreementAction.cs" />
    <Compile Include="CustomActions\Delete\DeleteAgreementActionConfig.cs" />
    <Compile Include="CustomActions\Download\DownloadDocAction.cs" />
    <Compile Include="CustomActions\Download\DownloadDocActionConfig.cs" />
    <Compile Include="CustomActions\Helpers\AdobeSignHelper.cs" />
    <Compile Include="CustomActions\Helpers\AttachmentHelper.cs" />
    <Compile Include="CustomActions\Helpers\ProxyProvider.cs" />
    <Compile Include="CustomActions\Models\Configuration\AttachmentConfig.cs" />
    <Compile Include="CustomActions\Models\Configuration\BaseConfiguration.cs" />
    <Compile Include="CustomActions\Models\GlobalStatusResponse.cs" />
    <Compile Include="CustomActions\Models\RemindRequest.cs" />
    <Compile Include="CustomActions\Models\SelfSignResponse.cs" />
    <Compile Include="CustomActions\Models\SendRequest.cs" />
    <Compile Include="CustomActions\Models\SendResponse.cs" />
    <Compile Include="CustomActions\Models\SingleStatusResponse.cs" />
    <Compile Include="CustomActions\Models\Statuses.cs" />
    <Compile Include="CustomActions\Models\UriModel.cs" />
    <Compile Include="CustomActions\Reminders\SendReminderAction.cs" />
    <Compile Include="CustomActions\Reminders\SendReminderActionConfig.cs" />
    <Compile Include="CustomActions\SendAndSignEnvelope\SendEnvelopeToEmbededSign.cs" />
    <Compile Include="CustomActions\SendAndSignEnvelope\SendEnvelopeToEmbededSignConfig.cs" />
    <Compile Include="CustomActions\SendEnvelope\SendEnvelopeAction.cs" />
    <Compile Include="CustomActions\SendEnvelope\SendEnvelopeActionConfig.cs" />
    <Compile Include="CustomActions\Status\CheckDocStatusAction.cs" />
    <Compile Include="CustomActions\Status\CheckDocStatusActionConfig.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="tmpKey.snk" />
    <None Include="WebCon.BpsExt.Signing.AdobeSign.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Publish\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="WEBCON.BPS.2026.SDK.Libraries" Version="26.1.1.26">
		<ExcludeAssets>runtime</ExcludeAssets>
	</PackageReference>
  </ItemGroup>
</Project>